---

  #- name: get consul package from s3
  #  aws_s3:
  #    bucket: "{{ bucket }}"
  #    object: "{{ consul }}"
  #    dest: /tmp/consul.pkg.tar.xz
  #    mode: get

  #- name: install consul
  #  command: pacman --noconfirm -U /tmp/consul.pkg.tar.xz

  - name: remove unnecessary files and directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/consul.d
      - /usr/lib/systemd/system/consul.service

  - name: create consul directories
    file:
      dest: "{{ item }}"
      state: "directory"
      mode: "0770"
      owner: "consul"
      group: "consul"
    with_items:
      - /etc/consul
      - /etc/consul/agent
      - /etc/consul/check
      - /etc/consul/service
      - /etc/consul/ui
      - /run/consul

  - name: copy consul@.service
    copy:
      dest: "/etc/systemd/system/consul@.service"
      src: "consul@.service"
    notify:
      - daemon-reload
