---

  - name: get consul package from s3
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ consul }}"
      dest: /tmp/consul.pkg.tar.xz
      mode: get

  - name: install consul
    command: pacman --noconfirm -U /tmp/consul.pkg.tar.xz

  - name: create consul directories
    file:
      dest: "{{ item }}"
      state: "directory"
      mode: "0770"
      owner: "consul"
      group: "consul"
    with_items:
      - /etc/consul.d
      - /etc/consul.d/agent/client
      - /etc/consul.d/agent/server
      - /etc/consul.d/agent/bootstrap
      - /etc/consul.d/ui

  - name: copy consul@.service
    copy:
      dest: "/etc/systemd/system/consul@.service"
      src: "consul@.service"
