---

  - name: add apache repository
    apt_repository:
      repo: ppa:ondrej/apache2
      update_cache: yes

  - name: install apache
    apt:
      name: apache2

  - name: place apache systemd service definition
    copy:
      src: apache.service
      dest: /etc/systemd/system/apache.service
