---

  - name: add apache repository
    apt_repository:
      repo: ppa:ondrej/apache2
      update_cache: yes

  - name: install apache
    apt:
      name: apache2

  - name: enable and start apache
    systemd:
      name: apache2
      state: started
      enabled: yes

  - name: enable apache modules
    command: a2enmod -q rewrite dir expires headers

  - name: remove index.html
    file:
      path: /var/www/html/index.html
      state: absent
