template {
  source = "/etc/consul-template/template/tsugi-config.php"
  destination = "/srv/http/tsugi/config.php"
}

vault {
  address = "http://vault.service.consul:8200"
  token = "{{ vault_token[lookup('env', 'ENVIRONMENT')] }}"
  renew_token = false
}
