---

  - hosts: localhost
    connection: local

    roles:

      # include the daemon-reload handler first
      - { role: systemd, tags: [ "systemd" ] }

      # meta roles
      - { role: admin, tags: [ "admin" ] }
      - { role: build, tags: [ "build" ] }
      - { role: control, tags: [ "control" ] }
      - { role: mysql, tags: [ "mysql" ] }
      - { role: nginx, tags: [ "nginx"] }
      - { role: proxy, tags: [ "proxy"] }
      - { role: web, tags: [ "web"] }
      #- { role: database, tags: [ "database" ] }
      #- { role: fleet, tags: [ "fleet" ] }
      #- { role: hub, tags: [ "hub" ] }
      #- { role: monitor, tags: [ "monitor" ] }
      #- { role: swarm, tags: [ "swarm" ] }

    post_tasks:

      - name: restart systemd-resolved
        systemd:
          name: systemd-resolved
          state: restarted
