---

  - hosts: localhost
    connection: local

    roles:

      # include the daemon-reload handler first
      - { role: systemd, tags: [ "systemd" ] }

      # meta roles
      - { role: admin, tags: [ "admin" ] }
      - { role: apache, tags: [ "apache" ] }
      - { role: build, tags: [ "build" ] }
      - { role: control, tags: [ "control" ] }
      - { role: mariadb, tags: [ "mariadb" ] }
      - { role: php-fpm, tags: [ "php-fpm" ] }
      #- { role: database, tags: [ "database" ] }
      #- { role: fleet, tags: [ "fleet" ] }
      #- { role: hub, tags: [ "hub" ] }
      #- { role: monitor, tags: [ "monitor" ] }
      #- { role: swarm, tags: [ "swarm" ] }
