---

  - hosts: localhost
    connection: local

    roles:

      # include the daemon-reload handler first
      - { role: systemd, tags: [ "systemd" ] }

      # meta roles
      - { role: admin, tags: [ "admin" ] }
      - { role: build, tags: [ "build" ] }
      - { role: control, tags: [ "control" ] }
      - { role: proxy, tags: [ "proxy"] }

      - { role: nginx-blue, tags: [ "nginx-blue" ] }
      - { role: nginx-green, tags: [ "nginx-green" ] }
      - { role: web, tags: [ "web" ] }

      - { role: tsugi-blue, tags: [ "tsugi-blue" ] }
      - { role: tsugi-green, tags: [ "tsugi-green" ] }

    post_tasks:

      - name: restart systemd-resolved
        systemd:
          name: systemd-resolved
          state: restarted
        tags: [ "network" ]
