---

  - hosts: localhost
    connection: local

    roles:

      # include the daemon-reload handler first
      - { role: systemd, tags: [ "systemd" ] }

      # meta roles
      - { role: admin, tags: [ "admin" ] }
      - { role: application, tags: [ "application"] }
      - { role: build, tags: [ "build" ] }
      - { role: control, tags: [ "control" ] }
      - { role: proxy, tags: [ "proxy"] }
      - { role: web, tags: [ "web"] }

    post_tasks:

      - name: restart systemd-resolved
        systemd:
          name: systemd-resolved
          state: restarted
        tags: [ "network" ]
