---

  - name: get unbound package from s3
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ unbound }}"
      dest: /tmp/unbound.pkg.tar.xz
      mode: get

  - name: install unbound
    command: pacman --noconfirm -U /tmp/unbound.pkg.tar.xz

  - name: template config
    template:
      src: unbound.conf.j2
      dest: /etc/unbound/unbound.conf
    notify:
      - reload unbound

  - name: systemctl daemon-reload
    command: systemctl daemon-reload

  - name: enable and start unbound
    systemd:
      name: unbound
      enabled: yes
      state: started

  - name: copy consul config
    copy:
      src: unbound.check.json
      dest: /etc/consul/checks/unbound.check.json
    notify:
      - reload consul@client
      - reload consul@server
