---

  #- name: get unbound package from s3
  #  aws_s3:
  #    bucket: "{{ bucket }}"
  #    object: "{{ unbound }}"
  #    dest: /tmp/unbound.pkg.tar.xz
  #    mode: get

  #- name: install unbound
  #  command: pacman --noconfirm -U /tmp/unbound.pkg.tar.xz

  - name: template config
    template:
      src: unbound.conf
      dest: /etc/unbound/unbound.conf
    notify:
      - reload unbound

  - name: create unbound drop-in directory
    file:
      path: /etc/systemd/system/unbound.service.d
      state: directory
      owner: unbound
      group: unbound
      mode: 0755

  - name: place unbound-before-systemd-resolved drop-in
    copy:
      src: 00-before-systemd-resolved.conf
      dest: /etc/systemd/system/unbound.service.d/00-before-systemd-resolved.conf

  - name: enable and start unbound
    systemd:
      name: unbound
      enabled: yes
      state: started

  - name: place unbound consul check definition
    copy:
      src: unbound.check.json
      dest: /etc/consul/check/unbound.check.json
    notify:
      - reload consul@client
      - reload consul@server
