---

  #- name: get unbound package from s3
  #  aws_s3:
  #    bucket: "{{ bucket }}"
  #    object: "{{ unbound }}"
  #    dest: /tmp/unbound.pkg.tar.xz
  #    mode: get

  #- name: install unbound
  #  command: pacman --noconfirm -U /tmp/unbound.pkg.tar.xz

  - name: template config
    template:
      src: unbound.conf
      dest: /etc/unbound/unbound.conf
    notify:
      - reload unbound

  - name: enable and start unbound
    systemd:
      name: unbound
      state: started
      enabled: yes

  - name: place unbound consul check definition
    copy:
      src: unbound.check.json
      dest: /etc/consul/check/unbound.check.json
    notify:
      - reload consul@client
      - reload consul@server
