---

  #- name: get unbound package from s3
  #  aws_s3:
  #    bucket: "{{ bucket }}"
  #    object: "{{ unbound }}"
  #    dest: /tmp/unbound.pkg.tar.xz
  #    mode: get

  #- name: install unbound
  #  command: pacman --noconfirm -U /tmp/unbound.pkg.tar.xz

  - name: template config
    template:
      src: unbound.conf
      dest: /etc/unbound/unbound.conf
    notify:
      - reload unbound

  - name: create unbound drop-in directories
    file:
      path: /etc/systemd/system/{{ item }}
      state: directory
    with_items:
      - unbound.service.d
      - systemd-resolved.service.d

  - name: place unbound systemd drop-in
    copy:
      src: 00-before-systemd-resolved.conf
      dest: /etc/systemd/system/unbound.service.d/00-before-systemd-resolved.conf

  - name: place systemd-resolved systemd drop-in
    copy:
      src: 00-after-unbound.conf
      dest: /etc/systemd/system/systemd-resolved.service.d/00-after-unbound.conf

  - name: systemd daemon-reload
    systemd:
      daemon_reload: yes

  - name: enable and start unbound
    systemd:
      name: unbound
      state: started
      enabled: yes

  - name: place unbound consul check definition
    copy:
      src: unbound.check.json
      dest: /etc/consul/check/unbound.check.json
    notify:
      - reload consul@client
      - reload consul@server
