---

  #- name: get unbound package from s3
  #  aws_s3:
  #    bucket: "{{ bucket }}"
  #    object: "{{ unbound }}"
  #    dest: /tmp/unbound.pkg.tar.xz
  #    mode: get

  #- name: install unbound
  #  command: pacman --noconfirm -U /tmp/unbound.pkg.tar.xz

  - name: template config
    template:
      src: unbound.conf
      dest: /etc/unbound/unbound.conf
    notify:
      - reload unbound

  - name: create /etc/systemd/system/unbound.service.d
    file:
      path="/etc/systemd/system/unbound.service.d"
      state="directory"

  - name: create /etc/systemd/system/systemd-resolved.service.d
    file:
      dest="/etc/systemd/system/systemd-resolved.service.d"
      state="directory"

  - name: copy 00-partof-systemd-resolved.conf
    copy:
      dest="/etc/systemd/system/unbound.service.d/00-partof-systemd-resolved.conf"
      src="unbound.service.d/00-partof-systemd-resolved.conf"
    notify:
      - daemon-reload
      - restart unbound

  - name: copy 00-partof-unbound.conf
    copy:
      dest="/etc/systemd/system/systemd-resolved.service.d/00-partof-unbound.conf"
      src="systemd-resolved.service.d/00-partof-unbound.conf"
    notify:
      - daemon-reload
      - restart systemd-resolved

  - name: systemctl daemon-reload
    command: systemctl daemon-reload

  - name: enable and start unbound
    systemd:
      name: unbound
      enabled: yes
      state: started

  - name: copy consul config
    copy:
      src: unbound.check.json
      dest: /etc/consul/check/unbound.check.json
    notify:
      - reload consul@client
      - reload consul@server
