---

  - name: copy zlogin
    copy:
      src: zlogin
      dest: /root/.zlogin

  - name: template ssh consul service
    template:
      src: ssh.service.json
      dest: /etc/consul/service/ssh.service.json
    notify:
      - daemon-reload
      - reload consul@client
      - reload consul@server
