---

  - name: create php packages directory
    file:
      state: directory
      path: /tmp/php

  - name: copy php packages
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: "/tmp/php/{{ item.key }}.pkg.tar.xz"
      mode: get
    with_dict: "{{ packages }}"

  - name: install php packages
    shell: pacman --noconfirm -U /tmp/php/*

  - name: place php.ini
    copy:
      src: php.ini
      dest: /etc/php/php.ini
    notify:
      - reload apache

  - name: enable php-apache
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      insertafter: "#LoadModule rewrite_module modules/mod_rewrite.so"
      line: "LoadModule php7_module modules/libphp7.so"
    notify:
      - reload apache

  - name: render php files with apache
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      insertafter: "LoadModule php7_module modules/libphp7.so"
      regexp: "<FilesMatch \\.php\\$>$"
      line: >
        <FilesMatch \.php$>
          SetHandler application/x-httpd-php
        </FilesMatch>

  - name: disable mpm_event_module
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "LoadModule mpm_event_module modules/mod_mpm_event.so$"
      line: "#LoadModule mpm_event_module modules/mod_mpm_event.so"
    notify:
      - reload apache

  - name: enable mpm_prefork_module
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so$"
      line: "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so"
    notify:
      - reload apache
