---

  - name: install php-fpm
    pacman:
      name: php-fpm
      state: present
      update_cache: yes

  - name: place php www.conf
    copy:
      src: www.conf
      dest: /etc/php/php-fpm.d/www.conf
    notify:
      - reload php-fpm

  - name: place php.ini
    copy:
      src: php.ini
      dest: /etc/php/php.ini
    notify:
      - reload php-fpm

  - name: create php directory
    file:
      path: /srv/php
      state: directory
      owner: http
      group: http
      mode: 0755

  - name: enable and start php-fpm
    systemd:
      name: php-fpm
      enabled: yes
      state: started

  - name: copy php-fpm consul check
    copy:
      src: php-fpm.check.json
      dest: /etc/consul/check/php-fpm.check.json
    notify:
      - reload consul@client
