---

  - name: install php-fpm
    pacman:
      name: php-fpm
      state: present
      update_cache: yes

  - name: place php www.conf
    copy:
      src: www.conf
      dest: /etc/php/php-fpm.d/www.conf
    notify:
      - reload php-fpm

  - name: place php.ini
    copy:
      src: php.ini
      dest: /etc/php/php.ini
    notify:
      - reload php-fpm

  - name: enable and start php-fpm
    systemd:
      name: php-fpm
      enabled: yes
      state: started

  - name: template php consul service files
    template:
      src: php.service.json
      dest: /etc/consul/service/php.service.json
    notify:
      - reload consul@client
