---

  - name: enable and start php-fpm
    systemd:
      name: php-fpm
      enabled: yes
      state: started

  - name: template php www.conf
    template:
      src: www.conf
      dest: /etc/php/php-fpm.d/www.conf
    notify:
      - reload php-fpm

  - name: place php.ini
    copy:
      src: php.ini
      dest: /etc/php/php.ini
    notify:
      - reload php-fpm

  - name: template php consul service
    template:
      src: php.service.json
      dest: /etc/consul/checks/php.service.json
    notify:
      - reload consul@client
