---

  - name: create php packages directory
    file:
      state: directory
      path: /tmp/php

  - name: copy php packages
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: "/tmp/php/{{ item.key }}.pkg.tar.xz"
      mode: get
    with_dict: "{{ packages }}"

  - name: install php packages
    shell: pacman --noconfirm -U /tmp/php/*

  - name: enable php-apcu
    lineinfile:
      path: /etc/php/conf.d/apcu.ini
      regexp: "extension=apcu.so$"
      line: "extension=apcu.so"
    notify:
      - reload apache

  - name: enable opcache
    copy:
      src: opcache.ini
      dest: /etc/php/conf.d/opcache.ini
    notify:
      - reload apache

  - name: enable pdo_mysql
    copy:
      src: pdo_mysql.ini
      dest: /etc/php/conf.d/pdo_mysql.ini
    notify:
      - reload apache

  - name: enable php-apache
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      insertafter: "#LoadModule rewrite_module modules/mod_rewrite.so"
      line: "LoadModule php7_module modules/libphp7.so"
    notify:
      - reload apache

  - name: render php files with apache
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      insertafter: "LoadModule php7_module modules/libphp7.so"
      line: "AddHandler application/x-httpd-php .php"
    notify:
      - reload apache

  - name: set index.php as default
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "DirectoryIndex index\\."
      line: "    DirectoryIndex index.php"
    notify:
      - reload apache

  - name: disable mpm_event_module
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "LoadModule mpm_event_module modules/mod_mpm_event.so$"
      line: "#LoadModule mpm_event_module modules/mod_mpm_event.so"
    notify:
      - restart apache

  - name: enable mpm_prefork_module
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so$"
      line: "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so"
    notify:
      - restart apache

  - name: enable cgi_module
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "LoadModule cgi_module modules/mod_cgi.so$"
      line: "    LoadModule cgi_module modules/mod_cgi.so"
    notify:
      - restart apache
