---

  - hosts: tag_Cluster_{{ lookup('env', 'ENVIRONMENT') }}_control

    tasks:

      - name: stop consul alerts
        service:
          name: consul-alerts
          state: stopped

#      - name: save consul kv
#        service:
#          name: consul-backup
#          state: started

      - name: settle...
        pause:
          seconds: 5

      - name: stop consul@bootstrap
        service:
          name: consul@bootstrap
          state: stopped

      - name: stop consul@server
        service:
          name: consul@server
          state: stopped

      - name: clear raft data
        shell: rm -rf /var/consul/raft/*
        warn: false
