---

  - name: install openvpn
    pacman:
      name: openvpn
      state: present
      update_cache: yes

  - name: install easy-rsa
    pacman:
      name: easy-rsa
      state: present
      update_cache: yes

  - name: template openvpn configuration
    template:
      src: server.conf
      dest: /etc/openvpn/server/server.conf

  - name: enable and start iptables
    command: systemctl enable --now iptables

  - name: copy iptables configuration
    copy:
      src: iptables.rules
      dest: /etc/iptables/iptables.rules
    notify:
      - reload iptables

  - name: enable forwarding in the kernel
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present
      reload: yes
      sysctl_set: yes
      sysctl_file: /etc/sysctl.d/ipforward.conf
