---

  - name: install apache
    yum:
      name: httpd
      state: present

  - name: set server name
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "ServerName .*:80$"
      line: "ServerName {{ lookup('env', 'HOST_IP') }}:80"
    notify:
      - reload apache

  - name: add server status handler to apache configuration
    blockinfile:
      path: /etc/httpd/conf/httpd.conf
      marker: "# Server Status"
      block: >
        <Location "/server-status">
          SetHandler server-status
          Order Deny,Allow
          Deny from all
          Allow from {{ lookup('env', 'HOST_IP') }}
        </Location>
    notify:
      - reload apache

  - name: add mpm_prefork_module settings
    blockinfile:
      path: /etc/httpd/conf/httpd.conf
      marker: "# mpm_prefork_module settings"
      block: >
        <IfModule mpm_prefork_module>
          StartServers 1
          MinSpareServers 20
          MaxSpareServers 60
          MaxRequestWorkers 200
          MaxConnectionsPerChild 4500
        </IfModule>
    notify:
      - reload apache

  - name: enable and start apache
    service:
      name: httpd
      state: started
      enabled: yes

  - name: template apache telegraf configuration
    template:
      src: apache.telegraf.conf
      dest: /etc/telegraf/telegraf.d/apache.telegraf.conf
    notify:
      - reload influxdb-telegraf
