---

  - name: copy telegraf from s3
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ telegraf }}"
      dest: /tmp/telegraf.pkg.tar.xz
      mode: get

  - name: install telegraf
    command: pacman --noconfirm -U /tmp/telegraf.pkg.tar.xz

  - name: template telegraf.conf to /etc/telegraf
    template:
      src: telegraf.conf
      dest: /etc/telegraf/telegraf.conf
      owner: telegraf
      group: telegraf
      mode: 0770
    notify:
      - restart influxdb-telegraf

  - name: start and enable telegraf
    #command: systemctl enable --now telegraf
    systemd:
      name: telegraf
      state: started
      enabled: yes

  - name: copy influxdb-telegraf consul check
    copy:
      src: influxdb-telegraf.check.json
      dest: /etc/consul/checks/influxdb-telegraf.check.json
    notify:
      - reload consul@client
      - reload consul@server
