---

  - name: create apache packages directory
    file:
      state: directory
      path: /tmp/apache

  - name: copy apache packages
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: "/tmp/apache/{{ item.key }}.pkg.tar.xz"
      mode: get
    with_dict: "{{ packages }}"

  - name: install apache packages
    shell: pacman --noconfirm -U /tmp/apache/*

  - name: create systemd drop-in directory
    file:
      state: directory
      path: /etc/systemd/system/httpd.service.d

  - name: place restart on failure drop-in
    copy:
      src: restart-on-failure.conf
      dest: /etc/systemd/system/httpd.service.d/restart-on-failure.conf
    notify:
      - daemon-reload

  - name: enable and start apache
    service:
      name: httpd
      state: started
      enabled: yes
