---

  - name: create destination directory
    file:
      path: "{{ directory }}"
      state: directory

  - name: clone tsugi project
    git:
      repo: "{{ repository }}"
      dest: "{{ directory }}"

  - name: place tsugi configuration
    copy:
      src: config.php
      dest: "{{ directory }}/config.php"

  - name: initialize tsugi database
    shell: >
      cd "{{ directory }}/admin";
      php upgrade.php |& tee /tmp/debug.txt
