---

  - name: create destination directory
    file:
      path: "{{ directory }}"
      state: directory

  - name: clone tsugi project
    git:
      repo: "{{ repository }}"
      dest: "{{ directory }}"
      force: yes

  - name: place tsugi configuration
    copy:
      src: config.php
      dest: "{{ directory }}/config.php"
