---

  - name: place environment.py
    copy:
      dest: /usr/local/bin/environment.py
      src: environment.py
      mode: 0700

  - name: place environment service
    copy:
      src: environment.service
      dest: /etc/systemd/system/environment.service
    notify:
      - daemon-reload

  - name: place configure service
    copy:
      src: configure.service
      dest: /etc/systemd/system/configure.service
    notify:
      - daemon-reload

  - name: create systemd drop-in directories
    file:
      dest: "{{ item }}"
      state: directory
    with_items:
      - /etc/systemd/journald.conf.d
      - /etc/systemd/system/systemd-journal-gatewayd.socket.d

  - name: place persistent journal configuration
    copy:
      src: journald.conf.d/00-persistent.conf
      dest: /etc/systemd/journald.conf.d/00-persistent.conf
    notify:
      - daemon-reload
      - restart systemd-journald

  - name: place systemd-journal-gatewayd socket configuration
    copy:
      src: systemd-journal-gatewayd.socket.d/00-socket.conf
      dest: /etc/systemd/system/systemd-journal-gatewayd.socket.d/00-socket.conf
    notify:
      - daemon-reload
      - restart systemd-journal-gatewayd.socket

  - name: enable and start systemd-journal-gatewayd.socket
    systemd:
      name: systemd-journal-gatewayd.socket
      state: started
      enabled: yes

  - name: create interface configuration files
    file:
      dest: /etc/systemd/network/{{ item }}.network
      state: touch
    with_items:
      "{{ interfaces }}"

  - name: allow interfaces to use loopback address for DNS
    lineinfile:
      path: /etc/systemd/network/{{ item }}.network
      insertafter: "^\\[Network\\]$"
      line: DNS=127.0.0.1
      state: present
    with_items:
      "{{ interfaces }}"
    notify:
      - restart systemd-networkd

  - name: set interfaces to use domain names
    lineinfile:
      path: /etc/systemd/network/{{ item }}.network
      insertafter: "^\\[DHCP\\]$"
      line: UseDomains=yes
      state: present
    with_items:
      "{{ interfaces }}"
    notify:
      - restart systemd-networkd
