---

  - name: place environment.py
    copy:
      dest: /usr/local/bin/environment.py
      src: environment.py
      mode: 0700

  - name: place environment service
    copy:
      src: environment.service
      dest: /etc/systemd/system/environment.service
    notify:
      - daemon-reload

  - name: place configure service
    copy:
      src: configure.service
      dest: /etc/systemd/system/configure.service
    notify:
      - daemon-reload

  - name: create systemd drop-in directories
    file:
      dest: "{{ item }}"
      state: directory
    with_items:
      - /etc/dnssec-trust-anchors.d
      - /etc/systemd/journald.conf.d
      - /etc/systemd/resolved.conf.d
      - /etc/systemd/system/systemd-journal-gatewayd.socket.d

  - name: place persistent journal configuration
    copy:
      src: journald.conf.d/persistent.conf
      dest: /etc/systemd/journald.conf.d/persistent.conf
    notify:
      - daemon-reload
      - restart systemd-journald

  # This isn't the best way to disable dnssec, see below.
  - name: place DNSSEC disable configuration
    copy:
      src: resolved.conf.d/dnssec.conf
      dest: /etc/systemd/resolved.conf.d/dnssec.conf
    notify:
      - daemon-reload
      - restart systemd-resolved

  # This is included because it is another way of
  # of disabling dnssec.
  # Per-domain method of disabling dnssec.
  - name: place DNSSEC negative trust anchors
    copy:
      src: "dnssec-trust-anchors.d/{{ item }}"
      dest: "/etc/dnssec-trust-anchors.d/{{ item }}"
    with_items:
      - consul.negative
      - local.negative
      - aws.negative
    notify:
      - daemon-reload
      - restart systemd-resolved

  - name: template search domain configuration
    template:
      src: resolved.conf.d/search-domain.conf
      dest: /etc/systemd/resolved.conf.d/search-domain.conf
    notify:
      - daemon-reload
      - restart systemd-resolved

  - name: place systemd-journal-gatewayd socket configuration
    copy:
      src: systemd-journal-gatewayd.socket.d/socket.conf
      dest: /etc/systemd/system/systemd-journal-gatewayd.socket.d/socket.conf
    notify:
      - daemon-reload
      - restart systemd-journal-gatewayd.socket

  - name: enable and start systemd-journal-gatewayd.socket
    systemd:
      name: systemd-journal-gatewayd.socket
      state: started
      enabled: yes

  - name: create interface configuration files
    file:
      dest: /etc/systemd/network/{{ item }}.network
      state: touch
    with_items:
      "{{ interfaces }}"

  - name: allow interfaces to use loopback address for DNS
    lineinfile:
      path: /etc/systemd/network/{{ item }}.network
      insertafter: "^\\[Network\\]$"
      line: DNS=127.0.0.1
      state: present
    with_items:
      "{{ interfaces }}"
    notify:
      - restart systemd-networkd

  - name: set interfaces to use domain names
    lineinfile:
      path: /etc/systemd/network/{{ item }}.network
      insertafter: "^\\[DHCP\\]$"
      line: UseDomains=yes
      state: present
    with_items:
      "{{ interfaces }}"
    notify:
      - restart systemd-networkd
