---

  - name: get influxdb package from s3
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ influxdb }}"
      dest: /tmp/influxdb.pkg.tar.xz
      mode: get

  - name: install influxdb
    command: pacman --noconfirm -U /tmp/influxdb.pkg.tar.xz

  - name: template influxdb config
    template:
      src: influxdb.conf.tpl
      dest: /etc/influxdb/influxdb.conf
    notify:
      - daemon-reload
      - restart influxdb

  - name: enable and start influxdb
    command: systemctl enable --now influxdb

  - name: wait until influxdb has started
    wait_for:
      host: "{{ lookup('env', 'HOST_IP') }}"
      port: 8085
      delay: 5

  - name: create influxdb telegraf database
    command: influx -host {{ lookup('env', 'HOST_IP') }} -port 8085 -execute "create database telegraf"

  - name: template influxdb consul service
    template:
      src: influxdb-{{ item }}.service.json.tpl
      dest: /etc/consul/checks/influxdb-{{ item }}.service.json
    items:
      - admin
      - http
      # - udp
    notify:
      - daemon-reload
      - reload consul@client
      - reload consul@server
