---

  - name: get influxdb package from s3
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ influxdb }}"
      dest: /tmp/influxdb.pkg.tar.xz
      mode: get

  - name: install influxdb
    command: pacman --noconfirm -U /tmp/influxdb.pkg.tar.xz

  - name: template influxdb config
    template:
      src: influxdb.conf
      dest: /etc/influxdb/influxdb.conf
    notify:
      - daemon-reload
      - restart influxdb

  - name: enable and start influxdb
    systemd:
      name: influxdb
      enabled: yes
      state: started

  - name: wait until influxdb has started
    wait_for:
      host: "{{ lookup('env', 'HOST_IP') }}"
      port: 8086
      delay: 5

  - name: create influxdb telegraf database
    command: influx -host {{ lookup('env', 'HOST_IP') }} -port 8086 -execute "create database telegraf"

  - name: template influxdb consul service
    template:
      src: influxdb.service.json
      dest: /etc/consul/service/influxdb.service.json
    notify:
      - daemon-reload
      - reload consul@client
      - reload consul@server
