---

  - name: set default shell to zshell
    command: useradd -D -s /usr/bin/zsh

  - name: set root user shell to zshell
    command: chsh -s /usr/bin/zsh root

  - name: clone satan-shell repository
    git:
      repo: "{{ satan_shell }}"
      dest: /usr/local/etc

  - name: install satan-shell for root user
    shell: >
      cd /usr/local/etc
      ./install.sh

  - name: add users
    user:
      name: "{{ item.name }}"
      group: users
      groups: wheel
    with_items: "{{ users }}"

  - name: set users authorized keys
    authorized_key:
      user: "{{ item.name }}"
      key: https://github.com/{{ item.github }}.keys
    with_items: "{{ users }}"
