---

  - name: set root user shell to zshell
    command: chsh -s /usr/bin/zsh root

  - name: clone satan-shell repository
    git:
      repo: "{{ satan_shell }}"
      dest: /usr/local/etc/satan-shell

  - name: place satan-shell settings file
    copy:
      src: settings.conf
      dest: /usr/local/etc/satan-shell/zsh.d/settings.conf

  - name: install satan-shell for root user
    shell: |
      cd /usr/local/etc/satan-shell
      ./install.sh

  - name: add users
    user:
      name: "{{ item.name }}"
      group: users
      groups: wheel
    with_items: "{{ users }}"

  - name: set users authorized keys
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ lookup('file', item.key) }}"
      exclusive: yes
    with_items: "{{ users }}"
