---

  - name: get main_repo key from consul
    consul_kv:
      key: tsugi/{{ lookup('env', 'ROLE') }}/main_repo
    register: main_repo

  - name: git clone the main repo to /var/www/html
    git:
      repo: "{{ main_repo['data']['Value'] }}"
      dest: /var/www/html
