---

  - name: copy mysql
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: /tmp/{{ item.key }}.pkg.tar.xz
      mode: get
    with_dict: "{{ packages }}"

  - name: install mysql
    command: pacman --noconfirm -U /tmp/{{ item }}.pkg.tar.xz
    with_items:
      - jemalloc
      - libmysqlclient
      - mysql-clients
      - mysql

  - name: start mysql
    systemd:
      name: mysqld
      state: started
      enabled: yes

  - name: wait for mysql to start
    wait_for:
      port: 3306

  - name: configure the tsugi database
    shell: echo "{{ script }}" | mysql -u root
    ignore_errors: yes

  - name: template mysql consul service definition
    template:
      src: mysql.service.json
      dest: /etc/consul/service/mysql.service.json
    notify:
      - reload consul@client
