---

  - name: copy mysql
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: /tmp/{{ item.key }}.pkg.tar.xz
      mode: get
    with_items: "{{ packages }}"

  - name: install mysql
    command: pacman --noconfirm -U /tmp/{{ item.key }}.pkg.tar.xz
    with_items: "{{ packages }}"
