---

  - name: create destination directory
    file:
      path: "{{ directory }}"
      state: directory

  - name: clone tsugi website
    git:
      repo: "{{ repository }}"
      dest: "{{ directory }}"
