---

  - name: create destination directory
    file:
      path: "{{ directory }}"
      state: directory

  - name: create grav directories
    file:
      path: "{{ directory }}/{{ item }}"
      state: directory
      owner: 33
      group: 33
    with_items: "{{ grav_directories }}"

  - name: clone tsugi website
    git:
      repo: "{{ repository }}"
      dest: "{{ directory }}"
