---

  - name: remove destination directory
    file:
      path: "{{ directory }}"
      state: absent

  - name: create destination directory
    file:
      path: "{{ directory }}"
      state: directory

  - name: clone tsugi website
    git:
      repo: "{{ repository }}"
      dest: "{{ directory }}"

  - name: create grav directories
    file:
      path: "{{ directory }}/{{ item }}"
      state: directory
      owner: http
      group: http
    with_items: "{{ grav_directories }}"
