---

  - name: copy ec2-user authorized keys to root
    copy:
      src: /home/ubuntu/.ssh/authorized_keys
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
    ignore_errors: yes

  - name: remove user ec2-user
    user:
      name: ubuntu
      remove: yes
      state: absent

  - name: remove group ec2-user
    group:
      name: ubuntu
      state: absent

  - name: set root user shell to zshell
    user:
      name: root
      shell: /usr/bin/zsh

  - name: clone satan-shell repository
    git:
      repo: "{{ satan_shell }}"
      dest: /usr/local/etc/satan-shell

  - name: place satan-shell settings file
    copy:
      src: settings.conf
      dest: /usr/local/etc/satan-shell/zsh.d/settings.conf

  - name: place satan-shell modules file
    copy:
      src: modules.conf
      dest: /usr/local/etc/satan-shell/zsh.d/modules.conf

  - name: install satan-shell for root user
    shell: |
      cd /usr/local/etc/satan-shell
      ./install.sh

  - name: add users
    user:
      name: "{{ item.name }}"
      group: users
      groups: sudo
    with_items: "{{ users }}"

  - name: set users authorized keys
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ lookup('file', item.key) }}"
      exclusive: yes
    with_items: "{{ users }}"
