---

  - name: copy ec2-user authorized keys to root
    copy:
      src: /home/ubuntu/.ssh/authorized_keys
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
    ignore_errors: yes

  - name: remove user ec2-user
    user:
      name: ubuntu
      remove: yes
      state: absent

  - name: remove group ec2-user
    group:
      name: ubuntu
      state: absent

  - name: set root user shell to zshell
    user:
      name: root
      shell: /usr/bin/zsh

  - name: add users
    user:
      name: "{{ item.name }}"
      shell: /bin/bash
      group: users
      groups: sudo
    with_items: "{{ users }}"

  - name: set users authorized keys
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ lookup('file', item.key) }}"
      exclusive: yes
    with_items: "{{ users }}"
