---

  - name: create destination directory
    file:
      path: "{{ directory }}"
      state: directory

  - name: clone tsugi project
    git:
      repo: "{{ repository }}"
      dest: "{{ directory }}"

  - name: template tsugi configuration template
    template:
      src: tsugi-config.php
      dest: /etc/consul-template/template/tsugi-config.php
      variable_start_string: '<<'
      variable_end_string: '>>'
      block_start_string: '<%'
      block_end_string: '%>'
    notify:
      - reload consul-template@tsugi-config

  - name: template tsugi-config consul-template configuration
    template:
      src: tsugi-config.toml
      dest: /etc/consul-template/config/tsugi-config.toml
    notify:
      - reload consul-template@tsugi-config

  - name: enable tsugi configuration consul-template
    systemd:
      name: consul-template@tsugi-config
      state: started
      enabled: yes

#  - name: initialize tsugi database
#    shell: >
#      cd "{{ directory }}/admin";
#      php upgrade.php |& tee /tmp/debug.txt

  - name: template tusgi-consul-vault-check.py
    template:
      src: tsugi-consul-vault-check.py
      dest: /usr/local/bin/tsugi-consul-vault-check.py
      mode: 0755

  - name: template tsugi-config consul check definition
    template:
      src: tsugi-config.check.json
      dest: /etc/consul/check/tsugi-config-{{ lookup('env', 'DEPLOYMENT') }}.check.json
    notify:
      - reload consul@client
