---

  - name: create destination directory
    file:
      path: "{{ directory }}"
      state: directory

  - name: clone tsugi project
    git:
      repo: "{{ repository }}"
      dest: "{{ directory }}"

  - name: template tsugi configuration template
    template:
      src: tsugi-config.php
      dest: /etc/consul-template/template/tsugi-config.php
      variable_start_string: '<<'
      variable_end_string: '>>'
      block_start_string: '<%'
      block_end_string: '%>'
    notify:
      - reload consul-template@tsugi-config

  - name: template tsugi-config consul-template configuration
    template:
      src: tsugi-config.toml
      dest: /etc/consul-template/config/tsugi-config.toml
    notify:
      - reload consul-template@tsugi-config

  - name: enable tsugi configuration consul-template
    systemd:
      name: consul-template@tsugi-config
      state: started
      enabled: yes

  - name: create efs directory
    file:
      state: directory
      path: /efs

  - name: mount efs partition
    mount:
      src: "{{ efs[lookup('env', 'ENVIRONMENT')] }}:/"
      path: /efs
      opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
      fstype: nfs4
      state: mounted

  - name: set efs owner and group
    file:
      state: directory
      path: /efs
      owner: www-data
      group: www-data
      recurse: yes

  - name: copy git to gitx
    copy:
      src: /usr/bin/git
      dest: /usr/local/bin/gitx
      mode: a+s
      owner: www-data
      group: www-data

  - name: initialize tsugi database
    shell: >
      cd "{{ directory }}/admin";
      php upgrade.php

  - name: update tsugi tools
    shell: >
      cd "{{ directory }}/admin";
      php update.php

  - name: template tusgi-consul-vault-check.py
    template:
      src: tsugi-consul-vault-check.py
      dest: /usr/local/bin/tsugi-consul-vault-check.py
      mode: 0755

  - name: copy tsugi-config consul check definition
    copy:
      src: tsugi-config.check.json
      dest: /etc/consul/check/tsugi-config.check.json
    notify:
      - reload consul@client
