---

  - name: copy consul-alerts
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: /tmp/{{ item.key }}.pkg.tar.xz
      mode: get
    with_dict: "{{ packages }}"

  - name: install consul-alerts
    command: pacman --noconfirm -U /tmp/{{ item }}.pkg.tar.xz
    with_items:
      - consul-alerts

  - name: copy consul-alerts systemd service
    copy:
      src: consul-alerts.service
      dest: /etc/systemd/system/consul-alerts.service
    notify:
      - daemon-reload

  - name: copy consul-alerts consul check
    copy:
      src: consul-alerts.check.json
      dest: /etc/consul/check/consul-alerts.check.json
    notify:
      - reload consul@client

  - name: enable and start consul-alerts
    systemd:
      name: consul-alerts
      state: started
      enabled: yes
