---

  - name: copy consul-alerts
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: /tmp/{{ item.key }}.pkg.tar.xz
      mode: get
    with_dict: "{{ packages }}"

  - name: install consul-alerts
    command: pacman --noconfirm -U /tmp/{{ item }}.pkg.tar.xz
    with_items:
      - consul-alerts

  - name: copy consul-alerts systemd service
    copy:
      src: consul-alerts.service
      dest: /etc/system/systemd/consul-alerts.service
