---

  - name: template tsugi-green consul service definition
    template:
      src: tsugi-green.service.json
      dest: /etc/consul/service/tsugi-green.service.json
    notify:
      - reload consul@client

  - name: create efs directory
    file:
      state: directory
      path: /efs

  - name: mount efs partition
    mount:
      src: "{{ efs[lookup('env', 'ENVIRONMENT')] }}:/"
      path: /efs
      opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
      fstype: nfs4
      state: mounted

  - name: set owner and group
    file:
      state: directory
      path: /efs
      owner: http
      group: http
      recurse: yes
