---

  - name: add php repository
    apt_repository:
      repo: ppa:ondrej/php
      update_cache: yes

  - name: install php
    apt:
      name: php7.1

  - name: install apache mod php
    apt:
      name: libapache2-mod-php7.1

  #- name: install php modules
  #  apt:
  #    name: php7.1-{{ item }}
  #  with_items:
  #    - mysql
  #    - curl
  #    - json
  #    - mbstring
  #    - zip
  #    - xml
  #    - gd
  #    - apc
  #    - intl

  - name: install php modules
    apt:
      name:
        - php7.1-mysql
        - php7.1-curl
        - php7.1-json
        - php7.1-mbstring
        - php7.1-zip
        - php7.1-xml
        - php7.1-gd
        - php7.1-apc
        - php7.1-intl
