---

  - name: add php repository
    apt_repository:
      repo: ppa:ondrej/php
      update_cache: yes

  - name: add mysql repository
    apt_repository:
      repo: ppa:ondrej/mysql-5.6
      update_cache: yes

  - name: install mysql-client
    apt:
      name: mysql-client

  - name: install php
    apt:
      name: php7.3

  - name: install apache mod php
    apt:
      name: libapache2-mod-php7.3

  - name: install php modules
    apt:
      name:
        - php7.3-mysql
        - php7.3-curl
        - php7.3-json
        - php7.3-mbstring
        - php7.3-zip
        - php7.3-xml
        - php7.3-gd
        - php7.3-intl
        - php-memchache
        - php-memchached
        - php-apcu

  - name: enable php modules
    command: phpenmod mysqlnd pdo_mysql intl apcu
    notify:
      - reload apache
