---

  - hosts: localhost
    connection: local

    roles:

      - { role: systemd, tags: [ "systemd" ] }

      - { role: ubuntu-test, tags: [ "ubuntu-test" ] }
      
      - { role: client-virginia-edu, tags: [ "client-virginia-edu" ] }
