---

  - hosts: localhost
    connection: local

    roles:

      - { role: systemd, tags: [ "systemd" ] }

      - { role: client-bb-learn, tags: [ "client-bb-learn" ] }
      - { role: client-brightspace-test, tags: [ "client-brightspace-test" ] }
      - { role: client-canvas, tags: [ "client-canvas" ] }
      - { role: client-moodle, tags: [ "client-moodle" ] }
      - { role: client-virginia-edu, tags: [ "client-virginia-edu" ] }

      - { role: tsugicloud-test, tags: [ "tsugicloud-test" ] }
