---

  - hosts: localhost
    connection: local

    roles:

      - { role: systemd, tags: [ "systemd" ] }

      - { role: client-virginia-edu, tags: [ "client-virginia-edu" ] }
      - { role: client-bb-learn, tags: [ "client-bb-learn" ] }
      - { role: client-cvtsugi, tags: [ "client-cvtsugi" ] }
      - { role: client-brightspace-test, tags: [ "client-brightspace-test" ] }
