---

  - name: create consul-template package directory
    file:
      state: directory
      path: /tmp/consul-template

  - name: copy consul-template packages
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: "/tmp/consul-template/{{ item.key }}.pkg.tar.xz"
      mode: get
    with_dict: "{{ packages }}"

  - name: install consul-template packages
    shell: pacman --noconfirm -U /tmp/consul-template/*

  - name: remove config file
    file:
      path: /etc/consul-template/config.hcl
      state: absent

  - name: create /run/consul-template
    file:
      path: /run/consul-template
      owner: consul
      group: consul
      state: directory
      mode: 0770

  - name: create /etc/consul-template/ directories
    file:
      path: /etc/consul-template/{{ item }}
      owner: consul
      group: consul
      state: directory
      mode: 0770
    with_items:
      - config
      - template

  - name: template consul-template systemd service
    template:
      src: consul-template@.service
      dest: /etc/systemd/system/consul-template@.service
    notify:
      - daemon-reload
