---

  - name: create nginx package directory
    file:
      state: directory
      path: /tmp/nginx

  - name: copy packages
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: /tmp/nginx/{{ item.key }}.pkg.tar.xz
      mode: get
    with_dict: "{{ packages }}"

  - name: install nginx packages
    shell: pacman --noconfirm -U /tmp/nginx/*
