---

  - name: update pacman cache
    pacman:
      update_cache: yes

  - name: copy nginx-mainline
    aws_s3:
      bucket: "{{ bucket }}"
      object: "{{ item.value }}"
      dest: /tmp/{{ item.key }}.pkg.tar.xz
      mode: get
    with_dict: "{{ packages }}"

  - name: install nginx-mainline
    command: pacman --noconfirm -U /tmp/{{ item }}.pkg.tar.xz
    with_items:
      - nginx-mainline

  - name: place nginx.conf consul-template
    copy:
      src: nginx.conf
      dest: /etc/consul-template/template/nginx.conf

  - name: place nginx.conf consul-template configuration
    copy:
      src: nginx.toml
      dest: /etc/consul-template/config/nginx.toml

  - name: start and enable consul-template@nginx
    systemd:
      name: consul-template@nginx
      state: started
      enabled: yes

  - name: start and enable nginx
    systemd:
      name: nginx
      state: started
      enabled: yes
